name: fluttershare
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  cached_network_image: ^2.2.0+1
  cloud_firestore: ^0.13.7
  image_picker: ^0.6.7+2
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  google_sign_in: ^4.5.1
  geolocator: ^5.3.2+2
  uuid: ^2.1.0
  image: any
  animator: ^2.0.1
  path_provider: ^1.6.11
  firebase_messaging: ^6.0.16
  timeago: ^2.0.26
  flutter_svg: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Assets/google sign in.png
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
